### ISSUE TITLE
Direct link to compare page does not work

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustc-perf#134]
As mentioned briefly in #132, query parameters for `/compare` do not seem to work when the page is loaded directly. For example, try navigating to http://perf.rust-lang.org/compare.html?date_a="2017-05-20T02%3A13%3A26%2B00%3A00"&date_b="2017-05-21T01%3A53%3A20%2B00%3A00"&crates={"list"%3A"All"%2C"content"%3Anull}&phases={"list"%3A"All"%2C"content"%3Anull}&group_by="crate" — notice that no comparison is shown. The JS error console show:
```text
Uncaught (in promise) SyntaxError: Unexpected token F in JSON at position 0
```
If, on the other hand, you go to http://perf.rust-lang.org/compare.html, select start `2017-05-20` and end `2017-05-21`, and click "submit", you'll get to the same URL, but the comparison shows up correctly.

**Comment by Mark-Simulacrum** [comment]
Thanks for noting this. I'll try to get a fix out soon, but it might be a while -- pull requests are always welcome, if you'd like, though (and I can probably help get started over IRC).
