### ISSUE TITLE
Show graphs by default

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustc-perf#139]
I personally find the wall of text on the home page to be pretty intimidating, and I still haven't really learned what all the numbers are.

I'd propose adding at least some (maybe not all) of the graphs to the home page. I think we'd want to clean up the UI (remove the giant checklists) and show the %-difference view by default (not absolute timing). I think we could sprinkle in some rss/memory measurements along with compile time measurements.

When combined with https://github.com/rust-lang-nursery/rustc-perf-collector/issues/11 I'd hope that we could get some nice clean graphs that are hopefully pretty consistent to show.

Note that https://arewefastyet.com/ also has graphs to start out with! I wonder how they got them so smooth...

**Comment by Mark-Simulacrum** [comment]
Closing as done. Some work remains to polish up the UI but that is separate from this issue.
