### ISSUE TITLE
track -Z no-trans as well as full compile time

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustc-perf#14]
Since that is what is important for IDEs etc.

**Comment by Mark-Simulacrum** [comment]
Can this be tracked via ignoring some passes, or does it do more than that?

**Comment by nrc** [comment]
it can, but it is not very future proof since the passes can change (e.g., they might move around in order or we might new ones) and/or we might execute different passes in -Zno-trans

**Comment by Mark-Simulacrum** [comment]
What about, say, running a file `fn main() {}` through rustc each time (or just using helloworld) and then using that? Or does the benchmarking not take enough time that tracking this will be a problem?

**Comment by nrc** [comment]
I'm not sure I understand the proposal - are you proposing using the dummy run to get a list of passes?

**Comment by Mark-Simulacrum** [comment]
Yeah, that was my idea. I don't know how long the runs take though--would a filter be worth it? There's probably a chance that there could be intra-pass optimizations in the future that would prevent this form of dummy run collection, so perhaps depending on it isn't a good idea.

**Comment by nrc** [comment]
building hello world is very quick, but actually so are most of the benchmarks (other than the bootstrap, where no-trans doesn't make sense), so if we would go to the effort of the dummy run, we may as well just re-measure.

**Comment by Mark-Simulacrum** [comment]
I'm thinking some form of marking/labeling the no-trans runs so we can have them as another kind in the UI is a good idea. Maybe a rule that no-trans runs call their crates "cratename--no-trans" and we can filter them that way?

**Comment by Mark-Simulacrum** [comment]
Adding a few crates with `cargo check` output is the required implementation step here. Suggestions welcome.

**Comment by Mark-Simulacrum** [comment]
We track `cargo check` now so I'm going to close this as obsolete.
