### ISSUE TITLE
Bench optimized builds

### ISSUE THREAD

**Issue by oyvindln** [rust-lang-nursery/rustc-perf#140]
Looking at this repo and rustc-benchmarks, it doesn't look like there is any benchmarks done of optimized/release mode builds. (Or am I missing something?)

Wouldn't it make sense to check the performance of this as well?

**Comment by Mark-Simulacrum** [comment]
We don't check compile times on release benchmarks currently. I don't think our current infrastructure can really support that (it'd take too long for most of these) but I'd be willing to look at options if we wanted it. cc @alexcrichton @nikomatsakis @aturon -- do we want this?

**Comment by alexcrichton** [comment]
Seems desirable to me! We probably don't want to double all our collected benchmarks but we can select a few "LLVM stressors" and see what optimized build times look like.

**Comment by Mark-Simulacrum** [comment]
@aturon Could you suggest someone (@nikomatsakis?) to find or select a few LLVM stressing benchmarks to enable release mode on? We can then add those.

**Comment by alexcrichton** [comment]
I'd imagine we already have some great candidates -- regex, syntex_syntax, tokio-webpush, etc.

**Comment by Mark-Simulacrum** [comment]
Let's promote the (newer) incremental regex. We can also promote tokio webpush, syntex_syntax will take too long I think. Marking for impl period, happy to mentor.

**Comment by michaelwoerister** [comment]
+1 for also testing optimized builds of regex.

**Comment by oyvindln** [comment]
If there is some mentoring available, I can have a go at this one.

**Comment by Mark-Simulacrum** [comment]
Sure! You can look at how https://github.com/rust-lang-nursery/rustc-perf/pull/151 was implemented, and you'd probably add `--release` to the `cargo rustc` invocations. Let's call it `regex-opt-version` and copy both `regex-0.1.80` and `regex.0.1.30` over. Let me know if you'd like further assistance!
