### ISSUE TITLE
Add crates.io!

### ISSUE THREAD

**Issue by carols10cents** [rust-lang-nursery/rustc-perf#142]
@alexcrichton [sayyyyys we cannnnnn](https://github.com/rust-lang/rust/issues/43789#issuecomment-323181710)

[crates.io's code](https://github.com/rust-lang/crates.io) builds on stable and I have no plans to change that for the foreseeable future

I also test on beta and nightly; this issue is prompted because I started seeing beta be over travis' memory limit - https://github.com/rust-lang/rust/issues/43789

**Comment by Mark-Simulacrum** [comment]
This change has deployed and the collection has started.
