### ISSUE TITLE
Allow for displaying absolute values in "graphs" view

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang-nursery/rustc-perf#144]
There are some benchmarks that are comparable to each other (e.g. the regex or the syntex ones) and for these it would be useful to be able to plot absolute values instead of change over time. This way we can compare how a non-incremental build fares against an incremental one or if the various incremental cases provide the expected speed ups.

**Comment by Mark-Simulacrum** [comment]
This could use someone with some frontend expertise. Probably just a toggle on the graph page which switches the percentage graph code on/off.

**Comment by Mark-Simulacrum** [comment]
Not currently, but I plan to soon, hopefully tonight.

**Comment by michaelwoerister** [comment]
Cool!
I took a quick look and it should not be too hard: 
* Add a radio button somewhere here: https://github.com/rust-lang-nursery/rustc-perf/blob/2b7e28f04b048de1bfe6ca8c4b607cc8f11ff7b9/site/static/index.html#L14
* If in "absolute mode", just don't do the conversion to percent here: https://github.com/rust-lang-nursery/rustc-perf/blob/2b7e28f04b048de1bfe6ca8c4b607cc8f11ff7b9/site/static/index.html#L64
* Set some sensible values here: https://github.com/rust-lang-nursery/rustc-perf/blob/2b7e28f04b048de1bfe6ca8c4b607cc8f11ff7b9/site/static/index.html#L139
* Make sure the whole thing is re-drawn when the radio button changes.

**Comment by Mark-Simulacrum** [comment]
Pushed and merged.
