### ISSUE TITLE
Add crate to the benchmarks

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#148]
https://github.com/White-Oak/rust-compilation-time-ram-regression from https://github.com/rust-lang/rust/issues/31157.

**Comment by Mark-Simulacrum** [comment]
Clone the repository into `collector/benchmarks`, add a Makefile for it (see other benchmarks), and submit a PR to the repo. Let me know if you have any questions!

**Comment by smt923** [comment]
I'd like to try working on this, if all goes well PR should be up in a little while
