### ISSUE TITLE
Potentially incorrect summary page median functionality

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#17]
I believe the intent with the [`summarise_data`](https://github.com/rust-lang-nursery/rustc-perf/blob/master/backend/perf.js#L174) function in the backend was to compute median times in the three weeks around the last week in the pulled data.

However, the current code doesn't do this, instead using only one week (probably the previous week from the last week being examined, if I'm reading the code correctly).

Is this intended?

(I noticed this while trying to understand what is happening in the current code while working on my Rust version of the code).

**Comment by nrc** [comment]
It is intended, the summary data is basically for answering the question 'did compiler performance get better or worse in the past week?' For the past 12 weeks its an extension of this - 'for the week up to the given data, did the compiler get better or worse?'
