### ISSUE TITLE
Display opt/non-opt side by side when screen size allows

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#170]
Experiment with a two column layout for the detailed graphs, showing the "opt" and the "non-opt" case side-by-side. That should fit well on a regular 16:9 or 16:10 display.

This might be best to do in something like CSS, actually, and to work well will probably want the maximum values on both graphs to be the same.

**Comment by michaelwoerister** [comment]
I think this is working out pretty well so far!

**Comment by Mark-Simulacrum** [comment]
Closing as done. We've since expanded to include three columns and that seems to work fairly well as well, though it's possible we're going to need to do some work for smaller display sizes, but that can be raised a separate issue later.
