### ISSUE TITLE
servo-script and servo-stylo benchmarks are missing the non-opt case

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang-nursery/rustc-perf#177]
We've been successfully collecting data for optimized builds of these crates, but for the unoptimized case we are missing the graphs. Do we know what the problem is here? Is it intentional for some reason?

cc @SimonSapin

**Comment by SimonSapin** [comment]
It looks like @Mark-Simulacrum made it so in https://github.com/rust-lang-nursery/rustc-perf/commit/5919f777beb4005e7298b25d51cecf099684b35d. Maybe because they take a lot of time?

**Comment by Mark-Simulacrum** [comment]
Yes, and I seem to recall an understanding that basically no one compiles these in non-opt mode anyway. Maybe that was wrong? I'm willing to change things here, but would rather avoid that if possible.

**Comment by SimonSapin** [comment]
Release mode takes forever to compile, I almost only work in debug mode or even `cargo check`. (Debug mode Servo takes forever to *run* but I run it much less than I compile it.)

In fact having numbers for `cargo check` might be interesting.

**Comment by michaelwoerister** [comment]
> In fact having numbers for cargo check might be interesting.

I agree. Ideally, we'd measure the `cargo check` times for all cases. But that would double our number of benchmarks. Not ideal...

**Comment by michaelwoerister** [comment]
Actually it might not be such a bad idea to have a third column for `cargo check` after all.

**Comment by michaelwoerister** [comment]
@SimonSapin, would you mind adding the debug case too? There's no reason not to test it.
@Mark-Simulacrum, will this need any updates to the UI? Or will it just work once measurements show up?

**Comment by Mark-Simulacrum** [comment]
Ah, probably, but shouldn't be too bad. So do we want `cargo build`, `cargo build --release` and `cargo check` columns for all of the entries?

**Comment by michaelwoerister** [comment]
Yes, let's give it a try. `cargo check` is used quite a bit. We can always remove it again if it causes problems.

**Comment by Mark-Simulacrum** [comment]
Sounds good. I'll try to get an implementation of this ready soon, but it'll probably be a week or so. Not sure yet when I'll get a chance.

**Comment by michaelwoerister** [comment]
Awesome, thanks!

On February 14, 2018 5:59:03 PM GMT+01:00, Mark Simulacrum <notifications@github.com> wrote:
>Sounds good. I'll try to get an implementation of this ready soon, but
>it'll probably be a week or so. Not sure yet when I'll get a chance.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang-nursery/rustc-perf/issues/177#issuecomment-365673381

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SimonSapin** [comment]
> I didn't even know passing --release to check was supported. Do we know if there's a difference there?

I didn’t know either, but I suppose it can affect which code is compiled (and typed-checked) through `cfg(debug_assertions)` for example.

**Comment by alexcrichton** [comment]
> since as far as I can tell, cargo rustc doesn't support any sort of --check argument

Would `cargo rustc --profile check` work?

**Comment by Mark-Simulacrum** [comment]
It should, yes, I'll try it and see. Thanks!

**Comment by Mark-Simulacrum** [comment]
@SimonSapin @michaelwoerister We should now be collecting and displaying `cargo check` data. I didn't change anything with regards to style and script-servo -- which collection suites (check, debug, and release) do we want to enable? All three?

**Comment by SimonSapin** [comment]
I tend to think that more data is generally better, but then I’m not personally working much on compiler performance and taking action based on this particular data so I don’t know at what point too much data becomes less readable.

**Comment by michaelwoerister** [comment]
I think we should have all three cases. Together they let us deduct how much time we spend in LLVM and how much of a difference optimizations make.

**Comment by Mark-Simulacrum** [comment]
I've updated to have all three cases though kept the iterations at 1 -- I think it'll take too long to do 3 iterations of servo crates -- though we can reevaluate later. I think that's it for this issue, so closing.
