### ISSUE TITLE
Some timing results are missing in 0b90e4e8cd068910f604f3e1fb5d03cc01f1658f

### ISSUE THREAD

**Issue by kennytm** [rust-lang-nursery/rustc-perf#178]
Repro steps:

1. Go to http://perf.rust-lang.org/compare.html?start=0b90e4e8cd068910f604f3e1fb5d03cc01f1658f&end=51b0b3734cbd0ca58c8be3512d53fce2d95f40dd&stat=instructions%3Au
2. Note that the page is blank
3. If you open developer tools, you'll find a JavaScript error

        TypeError: data.a.data[name] is undefined

    which means 0b90e4e8 is missing some crates.

According to the Summary graph, this may be happening between 957dc8de634886143195a1e1a1e1a7d047afe164 (2017 Dec 21st) to 0b90e4e8cd068910f604f3e1fb5d03cc01f1658f (2018 Jan 12th) inclusive.

**Comment by Mark-Simulacrum** [comment]
I've deleted 0b90e4e8cd068910f604f3e1fb5d03cc01f1658f from the collected data and we should recollect.
