### ISSUE TITLE
Start date computed 30, not 60 days before end date

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#18]
Comment [here](https://github.com/rust-lang-nursery/rustc-perf/blob/master/backend/perf.js#L827) states that a missing start date is computed as 60 days before the end date, but the code subtracts 30, not 60.

**Comment by Mark-Simulacrum** [comment]
Sounds good. Do you want a PR for the comment update, or should I not bother with it since the codebase is migrating to Rust and the comment can be updated then?

**Comment by nrc** [comment]
Either way is fine by me
