### ISSUE TITLE
Out of bound crash within handle_data

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang-nursery/rustc-perf#180]
```
assertion failed: end <= len
  10: site::server::handle_data
             at ./site/<panic macros>:3
             at src/server.rs:236
  11: site::server::handle_graph
             at src/server.rs:96
```

The only reason I can see is the vector being empty, and the end index unwrapped to 0+1.

Accessing this page directly crashes the server: http://perf.rust-lang.org/?start=2018-02-18&end=4ac2425879be115f4b71c8f15f30dc66eb6f5dac&absolute=true&stat=instructions%3Au

**Comment by Mark-Simulacrum** [comment]
Fixed in 8ab7db7.
