### ISSUE TITLE
sort, summarize in comparison view

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#184]
I think I would like it if the comparison view offered a better "summary" up front. @Mark-Simulacrum and I were brainstorming on IRC and came up with roughly this:

- For each test, show the min/max/avg %-age change. 
- Sort by %-age.
- Add a disclosure triangle to reveal the individual variants.

So it might look like this:

<details>
<summary>coercions Avg: 1.1% Min: -2.1% Max: 2.5%</summary>

```
clean | 1.34 | 1.37 | 2.4%
baseline incremental | 1.47 | 1.49 | 1.7%
clean incremental | 0.59 | 0.60 | 1.0%
patched incremental: println | 0.89 | 0.87 | -2.1%
patched incremental: add static arr item | 1.43 | 1.46 | 2.5%
```
</details>

**Comment by nikomatsakis** [comment]
My goal is to make more "actionable" summaries like this one automatic:

https://github.com/rust-lang/rust/pull/48411#issuecomment-368229726

**Comment by Mark-Simulacrum** [comment]
Implemented and deployed.
