### ISSUE TITLE
Allow for doing local perf runs

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang-nursery/rustc-perf#190]
For a short while, it was possible to do local perf-runs via `compare.py`. It would be great if we could enable something like this again (I don't how complicated that would be with the current setup).

**Comment by Mark-Simulacrum** [comment]
@nnethercote has done great work in this area, so I'm going to close this.

**Comment by nnethercote** [comment]
`collector bench_local` is the command to use. Run it with two different versions of rustc, and the run `site` on the output dir.

**Comment by nnethercote** [comment]
Better instructions are at https://github.com/nnethercote/rustc-perf/tree/master/collector/README.md
