### ISSUE TITLE
add keccak test

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#196]
@oli-obk [commented](https://github.com/rust-lang/rust/issues/49237#issuecomment-375322432):

> The keccak crate is a great benchmark for ridiculous numbers of locals and basic blocks. We should add it to the list of perf tests.

I'm not sure if they were serious, but I'm filing an issue anyway!

**Comment by michaelwoerister** [comment]
Looks like we have a test now?

**Comment by nnethercote** [comment]
@Mark-Simulacrum: keccak is in the suite. This can be closed.
