### ISSUE TITLE
Remove parser

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#220]
Most of the benchmarks in rustc-perf are either real code (e.g. clap-rs, crates.io, futures) or stress tests (e.g. deeply-nested, tuple-stress, unused-warnings). The two exceptions are helloworld and parser, which are toy programs.

I think it's reasonable for helloworld to be in the suite, to provide a lower bound on compilation time. But I think parser should be removed.
- It's a toy program, written (I think) by someone learning Rust.
- If you look at the code, it's actually exactly the same as helloworld, functionality-wise (there's extra code that isn't run).
- It's only about 700 lines of code.
- Profiles for it are quite similar to profiles for helloworld.

When I'm looking at profiles I almost always ignore it. I think its presence is a waste of human time and machine time.

@Mark-Simulacrum, what do you think?

**Comment by Mark-Simulacrum** [comment]
I don't personally have much of an opinion; it seems fine to keep, seems fine to remove; let's get @michaelwoerister and/or @nikomatsakis's opinions.
