### ISSUE TITLE
Collector Documentation Issues

### ISSUE THREAD

**Issue by porglezomp** [rust-lang-nursery/rustc-perf#221]
Some of the documentation on collector is a bit confusing to me, using it for the first time.

Two of the primary issues, one, because it uses the same `--output-repo` flag for committed and local builds, but the description is different. For the local build, should `--output-repo` still be a clone, or is it unrelated? Additionally, should the described `$CARGO` be a locally built cargo as well? I can't find a cargo in my build outputs.

I've been running it locally with apparently no output, several times, so the documentation (and maybe program feedback) isn't quite self-explanatory enough for me.

```
$ ./target/release/collector --output-repo ../rustc-timing/ profile_dhat rust0 --rustc ../rust0/build/x86_64-unknown-linux-gnu/stage2/bin/rustc --cargo /home/calebjon/.cargo/bin/cargo
```

**Comment by nnethercote** [comment]
Apologies for the quality of the docs; you're the first person who's had to use them for real :)

#223 should improve them to the point where all your questions are answered.

As for your sample command above, I would make these changes:
- Add `RUST_LOG=info` to the very start. This enables some logging, so you get progress indications.
- `--output-repo` doesn't have to point to a `rustc-timing` repo. Any old directory will suffice, even one that doesn't yet exist.
- I'm not sure why the `rust0` is in there. It should probably be removed.
- You can use ``--cargo `which cargo` `` to use the system Cargo, which should suffice.

**Comment by porglezomp** [comment]
`rust0` there was the `ID` value, I expected it to be accepted as a positional argument anywhere.

**Comment by porglezomp** [comment]
Also I *think* this is my last question, is the site able to visualize any of the other profilers, or only the benchmark run?

**Comment by nnethercote** [comment]
> Also I think this is my last question, is the site able to visualize any of the other profilers, or only the benchmark run?

Just the benchmark run. The other profilers produce various files that can be read directly, or post-processed with another tool, as described by https://github.com/rust-lang-nursery/rustc-perf/tree/master/collector#profiling-local-builds.
