### ISSUE TITLE
Track down a good way of parsing/serializing dates passed from/to the frontend

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#24]
Chrono struggles with parsing semi-arbitrary data.

Extracted comment:
> Also, I've been looking at [this existing URL](http://perf.rust-lang.org/graphs.html?start=Mon%20Jun%2013%202016%2019%3A51%3A42%20GMT%2B0000%20(UTC)&end=Wed%20Jul%2013%202016%2020%3A26%3A57%20GMT%2B0000%20(UTC)&kind=rustc&crates=total&phases=LLVM%20passes%2Ctranslation&group_by=phase) pointing at perf.rust-lang.org, and upon testing it with the current code, things break. I don't know of a good way to "best effort parse this date we're throwing at you" in Rust (and even in JS, truth be told). Without that, we'll either need to try and list all the cases we can think of (attempting parsing with each, failing, and moving on to the next one), or think of something else. Perhaps input sanitization? Regex-based search and recombine the input into something more readily parseable?

> Let me know if you think we shouldn't care about backwards compatibility with URLs (I think we should). I'm also not 100% certain how to generate the [URL](http://perf.rust-lang.org/graphs.html?start=Mon%20Jun%2013%202016%2019%3A51%3A42%20GMT%2B0000%20(UTC)&end=Wed%20Jul%2013%202016%2020%3A26%3A57%20GMT%2B0000%20(UTC)&kind=rustc&crates=total&phases=LLVM%20passes%2Ctranslation&group_by=phase) in that issue, my attempts don't seem to produce the `HH:MM:SS GMT+0000 (UTC)` part.

> ```
Error(Msg("while parsing Mon Jun 13 2016 19:51:42 GMT+0000 (UTC)"), (Some(ParseError(TooLong)), stack backtrace:
...
```

**Comment by Mark-Simulacrum** [comment]
Chrono's dates and times will soon support Serde as a deserialization/serialization option, but work to write standardized dates to the backend from the client is still necessary.

**Comment by Mark-Simulacrum** [comment]
I think standardizing all dates around `YYYY-MM-DD-HH-MM-SS` format in the UTC timezone or unix timestamps on both the client and server is the best solution here.

A script can be written to go through all of the processed data and change the dates to one of the chosen formats above.

I think that the first format out of the two is the best since it's relatively easy to parse on both the client and server, and is easier for humans to read and interpret.

**Comment by nrc** [comment]
We should use ISO 8601 format for the dates, in particular we should make the timezone explicit (with plain `Z` if we use UTC). I hope Chrono supports that.

**Comment by Mark-Simulacrum** [comment]
Looks like Chrono [supports it](https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html#method.to_rfc3339); though I'm not sure about the Z. Clientside, JS definetly supports it ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)).

**Comment by Mark-Simulacrum** [comment]
Clientside history URLs could be nicer to share if we went with YYYY.MM.DD (delimiter is unimportant) instead of ISO8601 specifically for storage in the URL, not transmission over the network.. especially since we only care about the date here.

**Comment by nrc** [comment]
ideally we'd have a date picker on the client and not care about the format

**Comment by Mark-Simulacrum** [comment]
Right, that's just the format in the input box though--I'm talking about the URL (e.g. the date in [this](http://perf.rust-lang.org/graphs.html?start=Thu%20Aug%2004%202016%2018%3A51%3A27%20GMT%2B0000%20(UTC)&end=Wed%20Aug%2017%202016%2023%3A38%3A44%20GMT%2B0000%20(UTC)&kind=rustc&crates=total&phases=total&group_by=crate) URL is.. hard to read).

**Comment by nrc** [comment]
hmm, true, although our URLs are so long and ugly I'm not sure how human-readable they can ever be

**Comment by Mark-Simulacrum** [comment]
`http://perf.rust-lang.org/graphs.html?start=2016-08-04&end=2016-08-17&kind=rustc&crates=total&phases=total&group_by=crate` reads much nicer though and is significantly shorter (actually human parseable).

**Comment by Mark-Simulacrum** [comment]
We (should, and do AFAICT) currently send ISO8601/RFC3339 dates to and from the frontend. Closing.
