### ISSUE TITLE
"patched incremental: println" results are haywire on the "Summary" graph

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#241]
From May 25 onward, the "patched incremental: println" results are haywire on the "Summary" graph, viz:
![perf](https://user-images.githubusercontent.com/1940286/40948931-a808cca4-68ae-11e8-8b92-55a50c8a8625.png)

Here's a screenshot from a local instance that is viewing only two runs:
![perf2](https://user-images.githubusercontent.com/1940286/40948852-27309d0a-68ae-11e8-9d6f-126e91afef70.png)
That makes it obvious that the "patched incremental: println" series is somehow getting two data points per run, when it should be getting one.

**Comment by Mark-Simulacrum** [comment]
Fixed on latest master and deployed.
