### ISSUE TITLE
The `script-servo` test is broken since 2018-07-16

### ISSUE THREAD

**Issue by kennytm** [rust-lang-nursery/rustc-perf#262]
Starting from rust-lang/rust@1ecf6929dc3b309cdfcb7239260777dab38242b9 (stabilize proc_macro) the `script-servo` test cannot be compiled:

```
error: cannot find macro `quote!` in this scope
  --> components/dom_struct/lib.rs:17:22
   |
17 |     let attributes = quote! {
   |                      ^^^^^

error[E0603]: module `quote` is private
 --> components/dom_struct/lib.rs:9:31
  |
9 | use proc_macro::{TokenStream, quote};
  |                               ^^^^^
```

**Comment by Mark-Simulacrum** [comment]
@alexcrichton, any chance you know what we should move to here?

**Comment by alexcrichton** [comment]
The `#![feature(proc_macro)]` directive should be switched to `#![feature(proc_macro_quote, use_extern_macros)]` I believe
