### ISSUE TITLE
add packed_simd as a benchmark

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustc-perf#268]
Building the tests of https://github.com/rust-lang-nursery/packed_simd (`cargo build --tests`) takes a while to build. It uses a lot of memory, it has dozens (probably hundreds) of modules, hundreds of trait implementations, lots of macros, etc. 

I think it would be a very interesting benchmark for rustc-perf

**Comment by nnethercote** [comment]
To me, the interesting question for this benchmark (or any other benchmark): does it stress rustc in ways that existing benchmarks do not?

**Comment by gnzlbg** [comment]
* it uses compiler plugins a lot to concatenate identifiers
* it exercises the features: `repr(simd)`, `simd_ffi`, .. pretty much completely

but to me the most interesting parts were that removing it from libstd reduced compile times of some crates by 7% even though they were not using it, that it has too many trait impls and modules which seem to be hitting rustc hard because the time it takes to compile is too long, and that it seems to be triggering weird behavior in some linkers when they get passed ~3000-4000 rcgus

**Comment by gnzlbg** [comment]
I've tried improving the compile-times, and the recent work is here: https://github.com/rust-lang-nursery/packed_simd/pull/84 but the -Z time-passes results are weird:

https://gist.github.com/gnzlbg/55e065756d17c34bc973ac6cb5203c5b

Total time: 6.46 min
codegen: 3.45 min

for building 160 tiny test functions.

**Comment by gnzlbg** [comment]
In fact, that PR shows something very weird. Currently, I split the tests into `cfg(...)` groups to avoid OOM errors. That is, the `packed_simd` crates is compiled `N` times, and each time a different `--cfg enable_test_{xyz}` is passed, to compile and run a subset of the tests. This has the downside that the `packed_simd` crate itself is also compiled `N` times, not just its test suite. 

That PR splits the tests into N different crates, so that `packed_simd` is compiled once. My expectation is that doing the same work once instead of 5 times would make things faster. 

Well... I cannot exactly pinpoint the issue (cargo metadata parsing?) but it does not only take longer, it takes almost `N` times longer, and compilation almost always OOMs. That's extremely weird.
