### ISSUE TITLE
html5ever is broken

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#274]
From https://perf.rust-lang.org/status.html:
```
error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
  --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/string_cache-0.2.29/src/lib.rs:71:13
   |
71 |     pub use atom;
   |             ^^^^
   |
note: the macro is defined here
  --> /tmp/.tmp7hXhhV/target/debug/build/string_cache-85a0b96525ad2556/out/atom_macro.rs:2:1
   |
2  | / macro_rules! atom {
3  | | (\"sdev\") => { $crate::Atom { unsafe_data: 0x2 } };
4  | | (\"onstart\") => { $crate::Atom { unsafe_data: 0x100000002 } };
5  | | (\"overflow\") => { $crate::Atom { unsafe_data: 0x200000002 } };
...  |
127| | (\"stroke-miterlimit\") => { $crate::Atom { unsafe_data: 0x4f400000002 } };
127| | }
   | |_^
```
@alexcrichton: can you advise on how to fix this?

**Comment by nnethercote** [comment]
@alexcrichton: is closing the right thing to do here? It seems like eventually the html5ever benchmark's code is going to have to change, right?

**Comment by alexcrichton** [comment]
Oh I just closed in favor of the duplicate, https://github.com/rust-lang/rust/issues/53495

**Comment by nnethercote** [comment]
There are two ways this issue could be fixed:
(a) rustc is modified somehow;
(b) the html5ever benchmark is modified somehow.

My impression is that (a) is not sufficient/appropriate, and that (b) will be necessary. In which case, leaving this issue open is the right thing to do. Make sense?

**Comment by Mark-Simulacrum** [comment]
That issue is tracking this same problem though?

**Comment by Mark-Simulacrum** [comment]
We've since fixed this -- html5ever compiles today.
