### ISSUE TITLE
Describe somewhere what the benchmarks measure, and how to measure yourself

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/rustc-perf#275]
I just realized that "baseline" and "clean" are the exact opposite of what I thought they were. "clean" sounds like it starts with a clean (empty) cache, and "baseline" like it would be the baseline, minimal cost of an incremental run with a hot cache. But actually it's the other way around.

Could the timing pages (like [this one](https://perf.rust-lang.org/compare.html?start=bf1e461173e3936e4014cc951dfbdd7d9ec9190b&end=86419f981b1097376824c441e716361ca9ccd558)) explain this somewhere? Like a note at the bottom, or a tooltip in the actual table, or so. Having space for such an explanation would anyway be useful, as that would also be a good space to describe how one can run that same benchmark against a local rustc -- which usually is the first thing I need to do when I see a regression.

(I am *still* working on figuring out how to reproduce this "incremental clean" regression. Took me at least an hour, at this point, due to running into issues like https://github.com/rust-lang/cargo/issues/5918.)

**Comment by Mark-Simulacrum** [comment]
Fixed in b52f4024.
