### ISSUE TITLE
Enable proc-macro2's nightly feature, to benchmark rustc's proc_macro implementation.

### ISSUE THREAD

**Issue by eddyb** [rust-lang-nursery/rustc-perf#277]
As pointed out in https://github.com/rust-lang/rust/pull/49219#issuecomment-414181092, we're likely not seeing much action involving the real `proc_macro` bundled with the compiler, because `proc-macro2`, by default, shims all the APIs, and interacts with the real `proc_macro` through `String`s (which was the only stabilized API for a while).
Any perf changes, in the implementation of the extended `proc_macro` APIs, may go by unnoticed.

cc @Mark-Simulacrum @nnethercote

**Comment by nnethercote** [comment]
This reminds me of #239.

**Comment by dtolnay** [comment]
Proc-macro2 now automatically wraps libproc_macro on sufficiently new compilers, so the benchmarks are already measuring proc_macro performance.
