### ISSUE TITLE
Unknown intended purpose of overwriting, data loss

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#28]
I'm not sure what the original intended purpose of the code involving `c_benchmarks_add` in `load.rs` was. However, I noticed that this means we overwrite existing data in these cases. None of these are recent, so it may not be too big a deal, but wanted to make sure we were aware of this, since it might lead to data loss in the future as well.
```
hyper.0.5.0 in hyper.0.5.0--2015-05-25-14-31-35.json
helloworld in helloworld--2015-05-25-14-31-35.json
html5ever-2015-05-15 in html5ever-2015-05-15--2015-05-25-14-31-35.json
regex.0.1.30 in regex.0.1.30--2015-05-25-14-31-35.json
rust-encoding.0.2.32 in rust-encoding.0.2.32--2015-05-25-15-45-57.json
regex-macros.0.1.30 in regex-macros.0.1.30--2015-05-25-14-31-35.json
```

@nrc did not recall either:
> Hmm, I don't recall either. I wonder if it is meant to coalesce data rather than overwrite it?
Add a line note

**Comment by Mark-Simulacrum** [comment]
It seems that the intended purpose is to coalesce the benchmark runs for each day into one index in the `data_benchmarks` vector. What I believe is happening is that two [or more] timing runs are occurring in each day. Should we average/median the two? Or just leave as-is? Seems to be a low priority issue.

**Comment by Mark-Simulacrum** [comment]
We consistently do more than one run per day in the bootstrap ("rustc") timings, and we currently just push into the array. It is unknown why bootstrap is different than the benchmarks. Testing shows that performing the merge in both bootstrap and benchmark is fine (tests pass); an implementation in #50 will be pushed soon.

**Comment by nrc** [comment]
Hmm, there might just be a bug here. There are certainly going to be multiple test runs per day and they should be stored separately, not combined into a per-day thing.

**Comment by Mark-Simulacrum** [comment]
Yeah, it's suspicious. I suspect that the actual truth lies somewhere in between: as shown in my comment on #50 despite many being done on the same day, we still overwrite very little. I suspect that there may be a bug in the processing scripts that pushes out multiple files per day despite only one run occurring/only records partial runs/we only do partial bootstrap runs? Not sure. It's certainly a weird situation.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of #53.
