### ISSUE TITLE
rust-timer bot re-executes command if the comment is edited

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang-nursery/rustc-perf#283]
If you post a comment with a command and edit it, the command is executed two times. It would be best to check the action when the GitHub webhook is received.

**Comment by Mark-Simulacrum** [comment]
This is semi-intentional (and harmless), since it means you can reduce noise by editing a past comment.

**Comment by pietroalbini** [comment]
Oh, ok.

**Comment by Mark-Simulacrum** [comment]
Hm, I'm pretty sure rustbot/triagebot does react to edits, it just diffs the parsed commands so it won't rerun unless you edit that particular command. But the bot here is simple enough that it's probably easier to just disable...
