### ISSUE TITLE
consider moving to grafana

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustc-perf#285]
@ishitatsuyuki posted this in the internal forums https://internals.rust-lang.org/t/trying-out-grafana-for-data-visualization/8344

It does look much more responsive than what we are currently using: https://snapshot.raintank.io/dashboard/snapshot/mbRr134JRP0J3dRMDm9xHmjEI0Zn9lIk?orgId=2

**Comment by ishitatsuyuki** [comment]
While Grafana is very good on UI, its functionality is limited to graphing only.

Do you have any idea on handling diffs?

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as it's a major refactor/change and at this point we aren't looking at such large changes. It's also unclear whether this would really give us any serious benefits (the graph code currently is not a major pain point).
