### ISSUE TITLE
Bustage due to recent self-profile changes

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#342]
I get this when running the `profile` or `bench` commands:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequence", line: 1, column: 19)'
```
The problem is this line: https://github.com/rust-lang-nursery/rustc-perf/blob/80826de37c486428f65a376d8aa0b5a8bb8dfcfe/collector/src/bin/rustc-perf-collector/execute.rs#L250

I think it assumes that the JSON is an array, but it's now an object (with keys/values).

I suspect https://github.com/rust-lang/rust/pull/58085 is the cause.

**Comment by nnethercote** [comment]
The performance of the new self-profile code is also unacceptable; it increases instruction counts by as much as 40%. See https://github.com/rust-lang/rust/pull/58085#issuecomment-462220399

**Comment by michaelwoerister** [comment]
Huh, I don't know that `rustc-perf` actually did anything with the json output. 

I think self-profiling shouldn't be done on perf.rlo yet until the data format has settled down.

**Comment by Mark-Simulacrum** [comment]
We can definitely stop collecting the data; we don't actually do anything with it yet - just load it and re-serialize it.

**Comment by michaelwoerister** [comment]
Yes, let's do this for now to unbreak things. The data will look differently in the future anyway.

**Comment by Mark-Simulacrum** [comment]
Perf should now be fixed.

**Comment by michaelwoerister** [comment]
Thanks, @Mark-Simulacrum!

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum: The compiler is still invoked with the `-Z self-profile` flag: https://github.com/rust-lang-nursery/rustc-perf/blob/56a77d04f6a73c7d8724ddde1d5628e28ab424e5/collector/src/bin/rustc-perf-collector/execute.rs#L233-L236

Given how much slower it makes the compiler in the current form, we should remove that too, I think.

**Comment by michaelwoerister** [comment]
Also, I left some notes on how to make self-profiling more efficient here: https://github.com/rust-lang/rust/issues/58372

**Comment by Mark-Simulacrum** [comment]
Fixed the invocation with self-profile flag; I had missed that in my initial search... thanks!

**Comment by michaelwoerister** [comment]
Thanks, @Mark-Simulacrum! Looks like perf.rlo is back to normal.
