### ISSUE TITLE
script-servo is broken again

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#354]
Buried among the *many* warnings is this error:
```
error[E0599]: no method named `trace` found for type `&for<\'r> fn(&\'r dom::node::Node) -> u16` in the current scope
   --> components/script/dom/treewalker.rs:470:10
    |
470 | #[derive(JSTraceable)]
    |          ^^^^^^^^^^^
    |
    = note: JSTraceable is a function, perhaps you wish to call it
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `trace`, perhaps you need to implement it:
            candidate #1: `dom::bindings::trace::JSTraceable`
```

**Comment by SimonSapin** [comment]
This sounds related to https://github.com/rust-lang/rust/issues/56105. Did the breakage occur when https://github.com/rust-lang/rust/pull/58592 landed?

The fix might be adding an impl, similar to https://github.com/servo/servo/pull/18327.

**Comment by nnethercote** [comment]
I removed and impl like that in #289 just last week. The conversation on IRC said the universes change was backed out, so seems like this is fallout from all that.

**Comment by nnethercote** [comment]
I pushed a fix for this.
