### ISSUE TITLE
OpenSSL 1.1.1 causes build bustage

### ISSUE THREAD

**Issue by nnethercote** [rust-lang-nursery/rustc-perf#466]
My Ubuntu 19.04 box has OpenSSL 1.1.1 installed. I get the following error message in the `openssl-sys` crate when building `crates.io`, `sentry-cli`, and `tokio-webpush-simple`:
```
This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5.0, 2.5.1, 2.5.2, 2.5.3, and 2.5.4, but a different version of OpenSSL was
found. The build is now aborting due to this version mismatch.
```
Newer versions of `openss-sys` accept OpenSSL 1.1.1, but we're stuck with old versions. The root problem is that `openssl-sys` is failing to follow semver by accepting 1.1.0 but rejecting 1.1.X :(  I'm not sure how to fix this.

**Comment by mati865** [comment]
Different OpenSSL versions aren't 1:1 compatible (I don't think it uses semver) so `openssl-sys` has to adjust to that, see changes required for OpenSSL 1.1.1b: https://github.com/sfackler/rust-openssl/commit/ab298d026477b5b5a07d8c98375ea6e85ddb59da#diff-2f153e0b1d130ce514c9869977eff0c4
This has landed in `openssl-sys = 0.9.42`.

Given the fact `openssl-sys` is just a bindings crate bumping it in the benchmarks shouldn't affect performance results.

**Comment by Mark-Simulacrum** [comment]
Yeah, this is indeed a problem. Bumping openssl-sys seems hard, as IIRC we need to go to 0.10 which would have downstream impacts as well. I think since we're not running anything though we may be able to create a dummy openssl in Rust with just `extern "C"` and such and replace openssl-sys with that? Not sure how easy that'd be, but maybe something worth taking a look at if updating -sys proves hard.

**Comment by mati865** [comment]
> Bumping openssl-sys seems hard, as IIRC we need to go to 0.10 which would have downstream impacts as well.

Turns out it's other way around, trivial `cargo update -p openssl-sys` fixes it's build error but `openssl` will fail with similar error because of aggressive version checks (which are mostly moved to `openssl-sys` in version 0.10).

**Comment by nnethercote** [comment]
#557 fixed this. All benchmarks are now compiling successfully on my Ubuntu 19.04 box. Yay!
