### ISSUE TITLE
Investigate cause of empty files

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#49]
These are the files I found to be empty:
```
regex.0.1.30--2016-06-21-04-21-09.json
issue-32062-equality-relations-complexity--2016-06-21-04-21-09.json
helloworld--2016-06-21-04-21-09.json
piston-image-0.3.11--2016-06-21-04-21-09.json
regex-macros.0.1.30--2016-06-21-04-21-09.json
inflate-0.1.0--2016-06-21-04-21-09.json
rust-encoding.0.2.32--2016-06-21-04-21-09.json
hyper.0.5.0--2016-06-21-04-21-09.json
jld-day15-parser--2016-06-21-04-21-09.json
issue-32278-big-array-of-strings--2016-06-21-04-21-09.json
rustc--2016-06-21-04-21-09.json
html5ever-2015-05-15--2016-06-21-04-21-09.json
```

**Comment by Mark-Simulacrum** [comment]
Looks like something went wrong specifically on 2016-06-21 at 4:21... the commit hash in the data repo is [c2e03496b69d0da8ce8d0bd738363db1e9a979c6](https://github.com/rust-lang-nursery/rustc-timing/commit/c2e03496b69d0da8ce8d0bd738363db1e9a979c6).

I suspect something may have gone wrong because the commit message includes timings from the output of `rustc -Z time-passes`. 

@nrc: Should this be a concern? Do we need to investigate further?

**Comment by nrc** [comment]
There are a bunch of times data collection failed. As long as we got back up collecting data, I don't think there's any reason to worry.

**Comment by Mark-Simulacrum** [comment]
Closing since this is not really actionable, there's no good way to investigate exactly what caused this. My original theory regarding the commit itself containing timing data may be correct, though I doubt it: the processing script should have at least added the commit and date header even if something went wrong later down the line.
