### ISSUE TITLE
detailed-query.html shows increase green

### ISSUE THREAD

**Issue by bjorn3** [rust-lang-nursery/rustc-perf#493]
https://github.com/rust-lang-nursery/rustc-perf/blob/8aa1a22d7f3bba2932b76e00067954919b07ec4e/site/static/detailed-query.html#L78-L84

pct > 1 means that the amount got bigger, however it is assigned the class positive which makes an element green.

**Comment by bjorn3** [comment]
And also shows positive percentages for decreasing values.

**Comment by Mark-Simulacrum** [comment]
Should be fixed. We were just comparing in the wrong direction. `positive` is color:red -- and you're not wrong that naming is horrible.
