### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bjorn3** [rust-lang-nursery/rustc-perf#494]
![Screenshot_20190930-125624](https://user-images.githubusercontent.com/17426603/65872828-c82a1c00-e381-11e9-9636-d6b6d83e19fc.png)

**Comment by nnethercote** [comment]
I got that for a bit too, but it's working again now.

**Comment by bjorn3** [comment]
I saw it again. The next moment it worked again though.

**Comment by bjorn3** [comment]
Its there again.

**Comment by bjorn3** [comment]
Works again.
