### ISSUE TITLE
View data sorted by check/opt/debug

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustc-perf#499]
Inspired by [this comment](https://github.com/rust-lang/rust/pull/64846#issuecomment-537197374) it might be a cool UI option to have an option to sort the comparison view by check/opt/debug numbers so you could at-a-glance see how each of the three categories roughly performs.

I think it'd also be cool to sort this by the 4 categories (clean/baseline incremental/clean incremental/etc) as well so you could at-a-glance see the relative impact of each scenario with a change.

**Comment by Mark-Simulacrum** [comment]
It's worth noting here that you can already type "check" or "opt" and such in the 'Filter benchmark builds' box and that'll filter down the view; it's not quite perfect but is a pretty fast way usually. We can probably add some presets for check/opt/debug fairly easily, though it would clutter the UI even more


<img width="390" alt="image" src="https://user-images.githubusercontent.com/5047365/66066951-93040200-e518-11e9-836e-1927dc826c22.png">

**Comment by alexcrichton** [comment]
I think I may just be blind, that's perfect!
