### ISSUE TITLE
Stop merging multiple runs with the same datetime into one

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#53]
When loading runs from disk, we can find more than one run has occurred on a given date. When this happens, we ideally want to keep all of the data. I propose that we continue to merge data, but instead of doing so by date, we should do so by the associated commit. The commit is what gives each run "uniqueness"; the date is associated metadata. We should still sort both `data_` vectors by the date, in order to ease display/manipulation and allow binary search functionality.

See #50 and #28 for previous discussion.

**Comment by Mark-Simulacrum** [comment]
@nrc: Do you agree with the proposal above? If not, we should discuss and edit.

**Comment by nrc** [comment]
Yes, I agree. To be clear, that means we might have multiple data-sets per date, so we should be careful on the frontend to deal with that.

**Comment by Mark-Simulacrum** [comment]
Leaving some notes for myself/whoever ends up working on this.

Data should now be stored in a `HashMap<CommitSha, CommitData>`, where CommitData is a struct containing data for both benchmarks and rustc. Dates don't really matter (though easier to think about for humans), so we can store the last date this commit was measured. (Future work could involve reading the commit's date from git).

Once this has been done, we want to modify the frontend graphs to be able to parse a format where the data given to them is an array of `crates -> timing, rss` for a given commit and date. The frontend will use the commit for the clickable points. The date will be used as it is currently.

I'm willing to mentor someone if they want to work on this, but will implement this myself soon (probably within a week of now).

**Comment by Mark-Simulacrum** [comment]
Removing the mentor label since I've started working on this and because I've run into some problems; I think I have a solution for them though.

**Comment by Mark-Simulacrum** [comment]
Initial implementation shows that changing the previous by-date overwriting to by-commit results in [a lot of overwrites](https://gist.githubusercontent.com/Mark-Simulacrum/3609890a80ce5c8d2d4c4524923d53e3/raw/ea3c78123f9cef926ccebd24aa79b5e8c76cf2fa/log).

Interestingly, it looks like a lot of data from 2015 is missing commits (the commit SHA is `000000`).

Discussion on IRC yielded that we want to archive the 2015 data since most of the problems stem from it.
