### ISSUE TITLE
502 Bad Gateway on custom page requests

### ISSUE THREAD

**Issue by RasmusWL** [rust-lang-nursery/rustc-perf#553]
Getting 502 Bad Gateway error (in alert box) when visiting the graph pages, most times (but not always); In some cases, the default view on https://perf.rust-lang.org/ does load.

I have had no success in loading https://perf.rust-lang.org/?start=2019-10-01&end=2019-11-01&absolute=true&stat=cpu-clock

![image](https://user-images.githubusercontent.com/1054041/68865012-5ff58680-06f2-11ea-9353-5e3555ddbc36.png)

Also seeing `no data yet, please wait` as the only thing on the page some times

I was hoping to show off the performance graphs, since I remember thinking it was a really cool concept. Do let me know if I can assist in debugging this in any way :blush: 

---

Using 

* Google Chrome Version 78.0.3904.97
* Ubuntu 18.04
* No adblock extensions

**Comment by Mark-Simulacrum** [comment]
Things should hopefully be better from now. "no data yet, please wait" is expected, should clear up in ~1-2 minutes.
