### ISSUE TITLE
breakdown of regression data by phase

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustc-perf#56]
for the summary page, show the regression data for each phase, not just a total

**Comment by Mark-Simulacrum** [comment]
Can probably be merged into #104 since that will show the breakdown by specific phase (we already show general, hard to read by-phase breakdown information).

**Comment by Mark-Simulacrum** [comment]
@nrc Do you agree with the above?

**Comment by nrc** [comment]
I think #104 is more about the graphs page, whereas this issue is about the summary page

**Comment by Mark-Simulacrum** [comment]
Right, but we link to the graphs page from each row/column on the summary page, so it will show the same data. It might be best to discuss this on IRC, though, I feel like we might be discussing two different concepts here :).

**Comment by Mark-Simulacrum** [comment]
I've been thinking about this some more, and I think it's hard to display per-crate per-phase data on the summary page. On the other hand, it's often helpful to immediately see which phase regressed without looking at the graph.

So I've thought up this design: on mouseover of any cell on the summary page, we can display a tooltip with one of two texts. If no phases or more than 5(?) phases regressed or improved my more than 0.5% or a raw time of 0.2(?) seconds, the tooltip can say "No specific phases regressed." However, if these conditions aren't true, we can display a list of phases:
```
LLVM Passes: 1.0s to 10.0s (+900%)
...
```

**Comment by nrc** [comment]
I wonder if we need an upper bound on the number of phases in the tooltip? In some cases it might be ridiculous, but it seems more informative to show the ridiculousness than a short message.

**Comment by Mark-Simulacrum** [comment]
Summary page is gone now.
