### ISSUE TITLE
Display absolute times, not just percentages, on the front page

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#59]
Percentages are useful but also kind of ... surprising. For example, a 1000% regression is "undone" by a 90% improvement. It'd be nice to see absolute times as well (also -- a percentage can look huge, but actually represent a small amount of time). It might be that we want to display this data only on hover or something.

**Comment by Mark-Simulacrum** [comment]
We now display changes in time in seconds on the front page, and percentages are completely gone. I've discussed with @nikomatsakis over IRC an idea to have a graph that display times as percentage changes normalized to 1 for each.

**Comment by nikomatsakis** [comment]
👍 to normalized graph

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang-nursery/rustc-perf/issues/144. A normalized graph is currently the *only* output, but we should show more.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang-nursery/rustc-perf/issues/144. A normalized graph is currently the *only* output, but we should show more.
