### ISSUE TITLE
Make it easy to go from front page to detailed info

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#60]
When you see a regression, it'd be great to be able to click on the test name and see more detailed data for just that test -- for example, the graph for total time on that benchmark and also the graphs for all individual compiler passes on that benchmark. This would probably be a simple step that would address #56 in an easier way. That is, if we could just click on the regression, we'd easily see if one particular compiler pass seems to have changed dramatically.

**Comment by Mark-Simulacrum** [comment]
Only major item left here is being able to click on the total column, but this is mainly an issue in principle.

Discussion on IRC also brought up that determining which phase is which in the graph is difficult, filed #104 to fix that.
