### ISSUE TITLE
Show when last update of data occurred

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#65]
Include a link to the data repository as a [manual] way to check if there has been updates since when the page was loaded/the server believes the latest update happened.

**Comment by Mark-Simulacrum** [comment]
Possibly also including a "ping this person on IRC (#rust-tools)? if you notice a problem"

**Comment by Mark-Simulacrum** [comment]
Options:
 - Do we want to show the time of the last pull (whether we pulled new data or not)?
    - Note: `stat -c %Y .git/FETCH_HEAD` seems to be a way of doing that, from [here](http://stackoverflow.com/a/9229377/4085230).
 - Should we just show the date of the last run the server knows about?
    - Easier, in fact almost effortless, but may not be entirely accurate (we may have collected since then but the server doesn't know about it).

**Comment by nrc** [comment]
For me, the second option sounds more useful - primarily this is a signal that all is OK, if it is not, we must do some more investigating in any case
