### ISSUE TITLE
Ability to run offline

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#70]
I really want the ability to run these benchmarks (or some subset) offline. This would complement #1 -- basically I could check a local build, save its results, and compare them against master (again running locally).

**Comment by nikomatsakis** [comment]
Actually, looking more at how things are setup, I realize that maybe this issue is easier than I thought. It seems like I just need to adapt the `process.sh` script in `rustc-benchmarks` a bit (and then probably adapt the code a bit in here to allow loading from a local directory I guess?).

**Comment by Mark-Simulacrum** [comment]
The code here already loads from a local directory; passed to the server as the first argument at startup. process.sh looks like it needs minimal modifications (mostly related to the dependency on being in `/home/ncameron/`).

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum great! :)

**Comment by nrc** [comment]
relative paths would be best, I don't recall if there is some reason not to use them though.

**Comment by Mark-Simulacrum** [comment]
I believe that we're almost good to go on this. The http server is certainly capable of running locally with no setup. The collection infrastructure should work as well with few problems, it just needs a way to specify a local copy of rustc/cargo. That should not be too hard to add, I will take a look once I finish updating the frontend here...
